CREATE TABLE [dbo].[MarketPlaceItems] (
    [ScrapeCompanyName]  VARCHAR (250) NULL,
    [ScrapeID]           SMALLINT      NULL,
    [ScrapeDate]         DATETIME      NULL,
    [CompanyName]        VARCHAR (250) NULL,
    [Location]           VARCHAR (250) NULL,
    [PhoneNumber]        VARCHAR (20)  NULL,
    [ProductName]        VARCHAR (250) NULL,
    [Category]           VARCHAR (50)  NULL,
    [Color]              VARCHAR (15)  NULL,
    [Condition]          VARCHAR (50)  NULL,
    [Doors]              VARCHAR (20)  NULL,
    [Drive]              VARCHAR (20)  NULL,
    [EngineManufacturer] VARCHAR (250) NULL,
    [FitsToManufacturer] VARCHAR (250) NULL,
    [FloorType]          VARCHAR (20)  NULL,
    [FuelType]           VARCHAR (20)  NULL,
    [HorsePower]         VARCHAR (20)  NULL,
    [Hours]              VARCHAR (20)  NULL,
    [MozendaItemID]      NCHAR (10)    NULL,
    [MozendaLastUpdated] VARCHAR (50)  NULL,
    [LeasingViewPrices]  VARCHAR (20)  NULL,
    [Length]             VARCHAR (20)  NULL,
    [LiftCapacity]       VARCHAR (50)  NULL,
    [LiftEndGate]        VARCHAR (20)  NULL,
    [LoadCapacity]       VARCHAR (50)  NULL,
    [Model]              VARCHAR (50)  NULL,
    [NumberOfRearAxles]  VARCHAR (20)  NULL,
    [Price]              VARCHAR (20)  NULL,
    [Quantity]           NCHAR (10)    NULL,
    [RentalMonthlyRate]  VARCHAR (20)  NULL,
    [RentalWeeklyRate]   VARCHAR (20)  NULL,
    [RentalViewPrices]   VARCHAR (20)  NULL,
    [SerialNumber]       VARCHAR (50)  NULL,
    [Sleeper]            VARCHAR (20)  NULL,
    [StockNumber]        VARCHAR (20)  NULL,
    [Suspension]         VARCHAR (50)  NULL,
    [Tires]              VARCHAR (20)  NULL,
    [Transmission]       VARCHAR (50)  NULL,
    [VIN]                VARCHAR (20)  NULL,
    [Wheels]             VARCHAR (20)  NULL,
    [Width]              VARCHAR (20)  NULL,
    [Year]               VARCHAR (4)   NULL,
    [ScrapeCompanyID]    SMALLINT      NULL,
    [Manufacturer]       VARCHAR (50)  NULL,
    [ImgURLLarge]        VARCHAR (450) NULL,
    [ImgURLSmall]        VARCHAR (450) NULL
);


GO

